### PR TITLE
Feature route list gui

### PR DESCRIPTION
**Pull request by fincamd**
Prototype of route card display. Components and css.

### CODE REVIEW

**Comment by fincamd** [comment]
#39 issue link

**Comment by fincamd** [comment]
Well, seems like that unless we use the components anywhere in the code this thing is going to complain...

**Comment by PabloFerMar** [comment]
So, now that I added those two basic tests, codecov is back at 100%. Now we can go back to showing the list in the App.js if we also change the test if you want.

**Comment by fincamd** [comment]
Just so you all know, I disabled consistent quotes usage. Meaning that codacy will no longer complain about using single quotes instead of double quotes.

**Comment by fincamd** [comment]
Well, it seems legit to me, merging to development

**Pull request merged**
